spring:
  application:
    name: read-xml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/read-xml?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: false
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200

es:
  index:
    my_test: hgh_test